version: '3'
services:
  node-app:
    container_name: 'express-node-app-container'
    build: .
    volumes:
      -./src:app/src:ro
    ports:
      -'4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=prod
    env_file:
      - ./.env
